### ISSUE TITLE
[RAID] & [Dungeons] -  [Spells] get interrupted

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#1]
**Description:**

A List of cast that seems to be interruptable but shouldnt.

**Current behaviour:**

This casts can be interrupted

[Bellowing Roar](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=36922#used-by-npc) casted by [Nightbane](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=17225) 
[Charred Earth](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30129) casted by [Nightbane](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=17225) 
[Smoldering Breath](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30210) casted by [Nightbane](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=17225) 
[Shadow Nova](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=30852) cast by [Prince Malchezaar](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15690)

**Expected behaviour:**

Casts should not be interruptable

**Steps to reproduce the problem:**

You know the trick.

**Comment by sveN295** [comment]
Fixed.
