### ISSUE TITLE
[Dungeon] [Sethekk Halls] Last boss can be perma interupted to ignore arcane explosion.

### ISSUE THREAD

**Issue by Farnsie** [Jinnaix/nemesis-bug-reporting#101]
Last boss (18473) - Can be perma interupted/CC to not cast his arcane explosion - where you are supposed to run and hide - we had a total of  5 interrupts and he just cast his mana shield.

Solution:

Maybe make him non stunable/immune and non interruptible cast - maybe issue where you use stun and it cancels out spells like rest of the bosses?

**Comment by sveN295** [comment]
This was a script issue. He is supposed to cast Arcane Explosion at 80, 50 and 25% of his health. Instead, he had that ability on a timer but was killed before it was due. Fixed.
