### ISSUE TITLE
[Heroic The Arcatraz] Zereketh the Unbound [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#11]
Boss ability broken: Void zone

What is it supposed to do: 
Void Zone: Zereketh spawns Void Zones randomly around the room, void zones deal approximately 1000 damage (Heroic: 2300-2700) per second.

What we have on the server at the moment:
The black circle is moving and following the targeted player

it's not supposed to move at all.

https://wowwiki.fandom.com/wiki/Zereketh_the_Unbound

**Comment by sveN295** [comment]
Fixed. The Void Zones had a faulty Creature Script.
