### ISSUE TITLE
[Heroic The Arcatraz] Wrath-Scryer Soccothrates [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#12]
The boss is missing 2 abilities and the only 1 is using is not working properly.

Missing abilities:
1- Fel Immolation: Roughly 425 fire damage per 3 sec. Only affects melee range.
2- Felfire Shock: Does a flame shock which does about 2000 damage on hit and ticks afterward for fire damage. Can't be cleansed.

Wrong ability usage:
Charge and Flamewave: Will knock back everyone in melee range, then charges (Charge) a random party member leaving behind a wall of fire (Flamewave) which deals about 2000 dmg a second so move out of it and spread out.

You can get knockback but that's it. No charge, no wall of fire, nothing else. 

https://wowwiki.fandom.com/wiki/Wrath-Scryer_Soccothrates

**Comment by sveN295** [comment]
He casts Fel Immolation and Felfire Shock just fine.

I'll have to do some heavy scripting for his Flamewave.

**Comment by sveN295** [comment]
Fixed. Some potential for cosmetic improvements for the future. 

We have to see how the Felfire damage is balanced.
