### ISSUE TITLE
[Heroic The Arcatraz] Harbringer Skyriss [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#13]
Boss is missing an ability: Dominate - Mind control, not dispellable. If used on a Rogue, uncontrolled Cloak of Shadows will break the effect prematurely. If used on a Mage, he may Polymorph your healer for the full 50 seconds.

Boss is interrupting his own cast by moving (just like Nefarian issue with fear). 
2 Spells that he his interrupting on his own;
1- Fear - Single target. Usually cast on a random non-tank target in melee range but will hit the tank and cause aggro drop if there are no other players in melee range. Dispellable, considered a magic effect.
2- Mind Rend - Random Target, Channeled, stuns for 3 seconds, ticks every second for 1250 shadow damage, 1600 on Heroic. Resistible and considered a stun so the full effect can be removed by stun-removing items and abilities. Cannot be dispelled.

This works:  Heroic mode only: Mana Burn - Random targeted mana burn burning around 1500 mana, dealing 750 shadow damage in the process. Not interruptible.

https://wowwiki.fandom.com/wiki/Harbinger_Skyriss

**Comment by sveN295** [comment]
Did some improvements to the script but we will have to see how it plays out with a full party.
