### ISSUE TITLE
[Queuing for RDF in TBC]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#19]
Being level 70 does not allow you to queu for level 70 normal dungeons even tho you do have access to queue for heroics. 

You should be able to queue for both Heroics (if you have the reputation keys) and Normal.

**Comment by Evilanemesis** [comment]
It actualy says: Your level is too high.

**Comment by Jinnaix** [comment]
You loose the ability to que random for normal Dungeons but you can still que for random heroic dungeons. You can still que for specific dungeons as long as your level still fits that dungeon.
As far as i know, this is intended behavior. RDF wasnt a thing back in TBC.
