### ISSUE TITLE
[Core] Achievement - Karazhan

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#21]
**Description:**

Killing Prince Malchezaar does not award achievement of Karazhan.

**Current behaviour:**

^

**Expected behaviour:**

Killing Prince Malchezaar should award achievement of Karazhan.

**Comment by Evilanemesis** [comment]
Just tried again and got the achievement. I guess someone else should try it and if it works for that person, close this issue.

**Comment by Jinnaix** [comment]
Cant replicate - closed.
