### ISSUE TITLE
[Core] [Raid] [Karazhan] Prince Malchezaar movement maps

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#22]
**Description:**

Prince Malchezaar can stuck at the wall.

**Current behaviour:**

Seems like movement maps can let him walk up but prevent him to walk down.
[Picture ](https://cdn.discordapp.com/attachments/627057676391809034/633276745159671808/unknown.png)

**Expected behaviour:**

Shouldnt happen.

**Comment by Jinnaix** [comment]
There are some spots where he can walk back down but these spots are rare. As soon as he is fully at the top of the border, he cant go back. Even a fight reset will keep him there.

Karazhan is one big areaID. Therefore no chance for disabling mmaps for the boss area.

As we cant cover the whole area with invisible walls (this would shrink the movement area for the raid too), my suggestion would be changing the script so that he despawns and respawns at a reset.  
In current state, not even a gm can bring him down from that outer border area.

**Comment by sveN295** [comment]
Added a workaround so the boss is reset when he starts climbing the walls.

**Comment by Jinnaix** [comment]
Since this Issue has the 'Cant Fix' and 'Core' label, im closing it.
