### ISSUE TITLE
[Dungeon] Escape From Durnholde Keep [Boss] Captain Skarloc - Missing adds

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#27]
**Description:**

Captain Skarloc is missing his adds. (Some minor visiual stuff is missing too)

**Current behaviour:**

Spawns without adds making the fight fairly easy.

**Expected behaviour:**

Captain Skarloc comes with two adds: a Warden (healer) and a Veteran (rogue).

**Comment by sveN295** [comment]
Fixed.
