### ISSUE TITLE
[Raid] Karazhan [Boss] Maiden of Virtue [Spell] Repentance

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#28]
**Description:**

[Repentance](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=29511) should break at receiving damage.

**Current behaviour:**

Players affected by [Repentance](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=29511) doesnt break free when receiving damage.

**Expected behaviour:**

Players affected by [Repentance](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=29511) should break free when receiving damage.

**Steps to reproduce the problem:**

You know the trick.

**Comment by sveN295** [comment]
Fixed.
