### ISSUE TITLE
[Dungeon] Shattered Halls [Boss] Grand Warlock Nethekurse

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#29]
**Description:**

When you approach Grand Warlock Nethekurse, he will have 4 non-elite Fel Orc Converts standing in front of him. After the 4th of these are killed (the order does not matter), Nethekurse will attack the group. Nethekurse has some humorous quips to say while the party is killing the Fel Converts. If the group takes too long to kill the last of the four, Nethekurse will kill it himself and aggro the party.

**Current behaviour:**

Seems like you can attack them one after another - they should engage all at once? After killing them, boss doesnt engange you - you need to start the fight.

**Expected behaviour:**

https://wowwiki.fandom.com/wiki/Grand_Warlock_Nethekurse 
Maybe needs to be validated with a retail video - Wiki is not always correct. Im unsure about the "all adds should attack you" part.

**Comment by Jinnaix** [comment]
According to [this video](https://www.youtube.com/watch?v=WSn0K7oyjk8) you can fight them one after another.

**Comment by Evilanemesis** [comment]
Boss has to engage after killing the 4th orc which is not happening at the moment.

**Comment by sveN295** [comment]
Boss engages after killing all four Peons now.

Fixed his script so he casts the correct abilities in his first phase and starts using Dark Spin in his second phase. 

To Do: Can't get the Void Zones to stop casting Consumption so they deal a bit too much damage on Heroic.
