### ISSUE TITLE
[Heroic and Normal The Mechanar] Bloodwarder Slayer [NPC]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#32]
Missing 2 abilities;
1- Chilling Touch 30 yd range — A chilling touch slows the target, increasing the time between attacks and lowering movement speed for 6 sec. Instant
2- Melt Armor — Reduces the armor of nearby enemies for 15 sec. Instant

**Comment by Jinnaix** [comment]
[Fixed](https://github.com/Jinnaix/Nemesis/commit/99d6b107fb155e9fe79c31588d358f8ac37c12f2)
