### ISSUE TITLE
[Heroic only The Mechanar] Mechanar Wrecker [NPC]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#34]
Missing 1 ability;

Glob of Machine Fluid (Heroic mode) 20 yd range — Shoots a glob of machine fluid at an enemy, dealing Nature damage and slowing movement speed by 50% for 10 sec. Instant

https://wow.gamepedia.com/Mechanar_Wrecker

**Comment by Jinnaix** [comment]
[Fixed](https://github.com/Jinnaix/Nemesis/commit/1f92c6735d40da8de94c0fbf93b220d97dc42541)

Fixed [19231](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=19231) & [19712](https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=19712#abilities) in the same process.
