### ISSUE TITLE
[Quest][Eversong Woods] Unexpected Results (ID 8488)

### ISSUE THREAD

**Issue by Vallox-Nemesis** [Jinnaix/nemesis-bug-reporting#36]
**Description:**

The quest, Unexpected Results, does not register completion when you kill the mobs that spawn, if they manage to engage her in combat. Once you kill Gharsul the Remorseless and the 2 accompanying Angershade's, the NPC, Mirveda, is meant to return to normal and you should be award quest credit for protecting her. Currently, she seems to get stuck in a non-interactive state (she engages in combat, shooting fireballs, if something attacks her, but nothing after the enemies are defeated).
I tried abandoning the quest as well but that didn't reset her either.

Quest: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=8488
Mobs: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15958 + 2 x https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=15656

**Current behaviour:**

The mobs spawn and attempt to attack Mirveda, who responds by casting fireballs if they manage to aggro her. Killing all 3 of the spawned adds (Gharsul + the 2 Angershades) should trigger quest credit but it currently does not if they manage to engage her in combat, and the NPC seems to get stuck in a non-interactive state (even abandoning the quest doesn't reset her and you can't pick it up again as a result).

I tested this again and killed them before they reached her and the quest awarded credit as expected.

I tested it a few more times and I believe I've found the specific cause that results in a bugged state: if you happen to kill the last add on her threat table while she is casting a fireball, she will not reset and you won't get quest credit. She will be stuck in a non-interactive state until the zone reloads/she dies and respawns.

**EDIT:**

After further testing, it seems the casting thing has nothing to do with this bug. Instead, it seems that it has to do with whether or not all of the adds engage with her during their initial run after being spawned. If you pull them all before they reach her, it works fine. If they all reach her and you kill them, it works fine. However, if you let only some of them reach her, she will bug out after they die.

**Expected behaviour:**

Killing Gharsul + the 2 Angershades that spawn should give you quest credit always. Mirveda should remain in an interactive state; if she engages in combat, you should be able to talk to her once she drops combat. Additionally, abandoning the quest should allow you to pick it up again and will respawn the adds.

**Steps to reproduce the problem:**

1. Accept the quest, Unexpected Results.
2. Let Gharsul reach and engage Mirveda but aggro the Angershades before they reach her.
3. Observe that the NPC gets stuck after Gharsul dies. Even if you reset the Angershades and let her kill them.

**Comment by Jinnaix** [comment]
Tested several things now :
Killed all 3 NPCs without getting her into the fight - quest awarded
Killed one/two NPCs with her being invovled in combat - quest awarded
Waited for her starting to cast Fireball at a NPC and then killed it before her cast finished with one/two/all NPCs - quest awarded

Cant replicate.

**Comment by Vallox-Nemesis** [comment]
Will test again but pretty sure closing the issue is a mistake at this time if nothing was changed.

**Comment by Jinnaix** [comment]
Found the issue - will see if i can fix this

**Comment by Jinnaix** [comment]
Spellfocus problem - will keep this for reference.
