### ISSUE TITLE
[Dungen] Shattered Halls [Boss] Warchief Kargath Bladefist [Spell] Blade Dance

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#38]
**Description:**

Movementspeed problem. Check Script to cover latest changes to movement types

**Current behaviour:**

Superslow

**Expected behaviour:**

Superfast

**Comment by sveN295** [comment]
For me he moved at a pretty high speed while doing Blade Dance. Additional testing required.

**Comment by Jinnaix** [comment]
2 valid Bugs here :
1)
Movementspeed for his Blade Dance is okay as long as you are on try 1.
As soon as you are on a second try, the movement speed for Blade Dance is superslow.
Maybe me->SetWalk(false); that is called only on reset results to this behavior.

2) Some strange situation can happen where he drops trough the ground into the lava. You cant complete the fight anymore. You need to move out of the boss area so he resets and goes back to his home position. I dont think we can solve that falling trough thing but a despawn and respawn on reset would be a good idea because he is still slightly stuck .

**Comment by sveN295** [comment]
Blade Dance now has the correct movement speed on every subsequent try.

To prevent him being stuck when 2. happens he now despawns on reset and respawns after a couple of seconds.
