### ISSUE TITLE
[Dungeon] Blood Furnance [Boss] Kelidan the Breaker Encounter

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#39]
**Description:**

You need to kill 5 Channelers before the Bossfight

**Current behaviour:**

According to Bug reports, there might be some weird respawn behavior of the Channelers.

**Expected behaviour:**

Should not respawn midfight.

**Comment by sveN295** [comment]
They seem to respawn if you kill them before they are engaged.
