### ISSUE TITLE
 [Mana-Tomb Heroic] Pandemonius [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#4]
What he is supposed to do:
Melee (Heroic): Melees for up to 5.6k shadow damage. That's 3000 DPS at 120 SR. Can be dodged, miss, parried or even be blocked (partial and full), but armor does nothing.

What he do right now:
Miss most (90%+) of his melee attacks on a **naked** 70. 

https://wowwiki.fandom.com/wiki/Pandemonius

**Comment by sveN295** [comment]
Can't replicate. My T4 geared Test-Paladin-Tank gets hit if he is not blocking/parrying/dodging/missing and my naked test char gets hit all the time.
