### ISSUE TITLE
[Dungeon] Blood Furnance [Boss] Kelidan the Breaker [Spell] Burning Nova - teleport

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#40]
**Description:**

Heroic Version should teleport everyone close to the boss

**Current behaviour:**
Needs to be checked :
```cpp
                if (BurningNova_Timer <= diff)
                {
                    if (me->IsNonMeleeSpellCast(false))
                        me->InterruptNonMeleeSpells(true);

                    Talk(SAY_NOVA);

                    me->AddAura(SPELL_BURNING_NOVA, me);

                    if (IsHeroic())
                        DoTeleportAll(me->GetPositionX(), me->GetPositionY(), me->GetPositionZ(), me->GetOrientation());

                    BurningNova_Timer = 20000 + rand32() % 8000;
                    Firenova_Timer= 5000;
                    Firenova = true;
                }
```
**Expected behaviour:**

Should work

**Additional Note:**

Burning Nova should be an non-interruptable spell with a cast bar to see the cast. Right now, there is no cast bar.

**Comment by sveN295** [comment]
I added the pull mechanic to the heroic version.

Im not sure the cast is supposed to have a cast bar, it's instant at the moment.

To Do: He should cast SPELL_BURNING_NOVA to self stun and receive a visual effect, this is not working. As a workaround he is rooted until he casts the nova now.
