### ISSUE TITLE
[Dungen] Shattered Halls [Boss] Warchief Kargath Bladefist Adds

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#44]
**Description:**

Add spawning behavior and starting adds are not fully blizzlike.

**Current behaviour:**

3 Assassines are already spawned near his home position. He doesnt spawn any Assassines infight. All other adds are spawned correctly. These 3 initial assassines arent respawned if you need another try for the boss. Since they dont belong here, ofc they shouldnt be respawned.
In addition, the Sharpshooters and the Assassines drop loot on kill, the guard adds dont. 

**Expected behaviour:**

As far as i could research, he doesnt start with 3 spawned Assassines. Instead he spawns them outside of the arena as soon as the fight starts to keep people on the platform. The arena has to exits where i think they should spawn.

> When aggroed Assasins spawn outside of his room so its important that you DO NOT have anyone outside the room. 3-4assasins will jump anyone outside the room.

**Additional Note:**

While researching, i found this - doesnt happen at our core at the moment - maybe include it? : 

> If you sneak past Warlord O'mrogg, he will pull all the way to Bladefist when you engage the fight.

**Comment by sveN295** [comment]
Fixed the boss script. He now spawns 3 Assassins each at the entrance and exit when engaged and despawns them when he resets. 

Might include the O'mrogg pull later.
