### ISSUE TITLE
[Quest][NPC] Natural Remedies Quest is Not Being Offered (Possible NPC Bug)

### ISSUE THREAD

**Issue by Vallox-Nemesis** [Jinnaix/nemesis-bug-reporting#46]
**Description:**

The quest, Natural Remedies, should be offered as a follow up quest from Earthbinder Galandria Nightbreeze, after completing the previous quest. There is an event where you have to kill a mob that spawns, after which, she should return to normal and offer the quest. But she doesn't seem to offer it afterwards.

Quest: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?quest=10351
NPC: https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?npc=19294

**Current behaviour:**

The quest chain stops after turning in The Earthbinder. The NPC doesn't offer Natural Remedies like she should.

**Expected behaviour:**

Natural Remedies should be available after turning in The Earthbinder (once the NPC has returned to normal - requires killing the spawned add or having it despawn).

**Steps to reproduce the problem:**

1. Complete The Earthbinder.
2. Kill the add that spawns.
3. Observe that the NPC doesn't offer Natural Remedies afterwards.

Note: this might be a script issue similar to the issue the quest Unexpected Results. I will test this again to see if it happens or if it's just a fluke.

**Comment by Vallox-Nemesis** [comment]
I tested it again on another character, and it looks like the NPC is in a bugged state. I cannot turn in the previous quest, The Earthbinder because she is in some stuck state.

**Comment by Jinnaix** [comment]
[Fixed](https://github.com/Jinnaix/Nemesis/commit/d46715ad837e454ff77f60a8c44394036aef7d6f)

**Comment by Vallox-Nemesis** [comment]
Links to 404 not found. Private repository or something?

**Comment by Jinnaix** [comment]
exactly :)
