### ISSUE TITLE
[Crypts Heroic] Shirrak the Dead Watcher [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#5]
This bug is also applying to Normal version of the boss

Missing an ability;

Focus fire: Shirrak emotes "Shirrak the Dead Watcher focuses his energy on <target>" (this is actually a "raid message" type message, not an emote that only shows up as text). He places a static (non-targetable) beacon under one player; after 3-5 seconds, the beacon will "explode" and emit several pulses of AoE fire damage. This is about 1650 fire damage per hit in normal mode. In Heroic this is more like 3500. This is by far his most dangerous ability, and much of the fight relies on keeping good positioning and quickly reacting to this attack.

https://wowwiki.fandom.com/wiki/Shirrak_the_Dead_Watcher

**Comment by sveN295** [comment]
He was casting the ability, but only if there is more than one person in the fight.

Regardless, i improved the script a bit.
