### ISSUE TITLE
[Normal and Heroic The Botanica] Warp Splinter [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#52]
Ability; Spawn Treants - spawn 6+ treants (~3000hp) under the trees around the area which slowly move towards the group. They despawn after ~20 seconds and heal the boss for the total remaining health of the treants that are still alive (~1/4 of his HP maximum). He uses this ability every ~45 seconds after the first one.

Bug: They dont despawn after 20 seconds so they never heal the boss. 
Even after 45 seconds, I had a 2nd group of treants (12 total) and none of them for despawning. 

If they dont despawn, they dont heal the boss, making this fight super easy and adds not important to manage. 

https://wowwiki.fandom.com/wiki/Warp_Splinter

**Comment by sveN295** [comment]
Fixed.
