### ISSUE TITLE
[Item] Doomplate Battlegear 2-Set Bonus Not Granting Spell Hit

### ISSUE THREAD

**Issue by Vallox-Nemesis** [Jinnaix/nemesis-bug-reporting#53]
**Description:**

The Doomplate Battlegear, https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?itemset=661, is not granting any spell hit from its 2-piece bonus, which grants 35 hit rating. The melee hit rating is granted, but it does not grant any spell hit rating.

**Current behaviour:**

Only melee hit rating is granted from the set bonus.

**Expected behaviour:**

It should also grant spell hit rating (equal to 43.75 spell hit rating if my calculations are correct), because all hit rating applies to both melee and spell hit rating, unless otherwise explicitly stated on the item.

**Steps to reproduce the problem:**

1. Equip any 2 pieces of the Doomplate Battlegear set.
2. Observe that only melee hit rating is granted.

**Comment by Jinnaix** [comment]
I need to do additional research for this.

**Comment by Vallox-Nemesis** [comment]
Hmm, research what exactly? Hit rating is hit rating :) Every single item with "hit rating" has worked this way so far. All such hit rating gives +X melee hit chance, which also provides +1.25X spell hit chance. Hybrid classes like paladins and DKs have such hit rating on their gear, and it provides them with spell hit too. Otherwise they would be missing way too much with their spells.

**Comment by Jinnaix** [comment]
Research how to handle this to be specific. Sure, hit rating is hit rating as of patch 3.0.0.
But this Set-Bonus for example is not a simple +stats like you get from an item. It applies a hidden spell as an aura. This hidden spell has a specific function. In this case, it increases melee and range hit but NOT spellhit.

**Comment by Vallox-Nemesis** [comment]
I see. If this helps, the Desolation Battlegear's 2-set bonus has the intended functionality:
https://tcubuntu.northeurope.cloudapp.azure.com/aowow/?spell=37609
Maybe just have it use this aura instead of the one it currently has, if that's a simple fix.

**Comment by sveN295** [comment]
Doomplate Battlegear now also grants Spell Hit Rating. I preemptively applied the same fix to the Leather Agility set.
