### ISSUE TITLE
[Heroic The Mechanar] Gatewatcher Iron-Hand [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#54]
Poison ability named Stream of Machine Fluid is applied as a buff instead of a debuff. Can't cleanse it.

Ability Jack Hammer: Does an AoE centered on himself hitting for around 1000-1500 on regular and about 2500 on Heroic around 8 times in a short time. He stops moving when he does this, so all you have to do is run away to avoid it. 
NPC is still doing normal damage in Heroic mode. 

https://wowwiki.fandom.com/wiki/Gatewatcher_Iron-Hand

**Comment by sveN295** [comment]
Jack Hammer now does more damage in Heroic than in Normal.
