### ISSUE TITLE
[Heroic The Mechanar] Mechano-Lord Capacitus [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#55]
Boss is doing normal abilities in Heroic mode, they are not supposed to trigger in Heroic mode, here is the 2 abilities;
1- Reflective Damage Shield: (Red glow) - Inflicts 750 damage on melee attackers when struck. Normal mode only.
2- Reflective Magic Shield : (Green glow) - 100% chance to reflect spells to the caster. Normal mode only.

He seems to to make enough bombs when you compare to the other videos I found 11 years ago. 
https://www.youtube.com/watch?v=uqil91lzNV4  go at 3:30

Another bug found on him;
He seems to not trigger the Negative charge, Out of the 20 charges I got, they were all Positives. 

His damage also seems to be on Normal mode.

**Comment by sveN295** [comment]
Doesn't cast his Normal Abilities in Heroic any more. Also applies Negative Charge now.
