### ISSUE TITLE
[Heroic The Mechanar] Nethermancer Sepethrea [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#56]
Every abilities are working except 1 thing;

Three Raging Flames spawn, rather than two. As of 2.2.0, the elementals act like the Normal mode elementals, except that they run at 80% speed, not 50%.

Right now on the server, they are still running at 50% speed.

**Comment by sveN295** [comment]
Script fixed.
