### ISSUE TITLE
[Normal and Heroic The Mechanar] Pathaleon the Calculator [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#59]
1st bug;
**How is is supposed to be**;
This fight is naturally more difficult than normal mode. In addition to his normal abilities, Pathaleon now has an arcane explosion with a two-second cast time that hits for around 2000 damage. It is possible for all but the tank and melee to avoid it, and it appears to have a 10-second cooldown. (This AoE is interruptible. A rogue can Kick, or a warrior can Shield Bash it while in progress. Also, Pathaleon is susceptible to mind numbing poison, which will give you a touch more time to kick the arcane explosion.)

**How is it right now**;
Arcane explosion is instant cast.

2nd bug;
**How is it supposed to be**;
The best place to fight Pathaleon is in his room at the end of the walkway. The first thing to note is that he will spawn the 3 arcane elementals every 30-45 seconds. They have a decent amount of hit points and the arcane missiles hit for about 800. They will all despawn when the Pathaleon is down to 20% health. Another thing to watch for is that Pathaleon will mind control the second person in proximity to him frequently. This player will be mind controlled for about 8-10 seconds, during that time heal the boss or attack party members. A good way to handle this, is to crowd-control the mind-controlled player and dispel it afterward if possible. Other than that, he will melee the main tank and does not hit incredibly hard.

**How is it right now**;
Doesnt summon any adds

https://wowwiki.fandom.com/wiki/Pathaleon_the_Calculator

**Comment by sveN295** [comment]
Script is fixed.
