### ISSUE TITLE
[Karazhan] Opera Event [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#6]
Wizard of Oz,

Only Dorothee should start engaging fight, then after approx 10seconds, Roar comes in, after another 10 seconds approx, Strawman comes in and after 10 seconds, Tinhead comes in (engage).

What is the issue? The 4 of them engage fight at the first second. 

https://wowwiki.fandom.com/wiki/Wizard_of_Oz

**Comment by sveN295** [comment]
Can't replicate, they don't engage at the same time.
