### ISSUE TITLE
[Heroic Slave Pens] Mennu the Betrayer [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#63]
Boss is summoning 4 different kind of ward/totems, but none of them are doing their abilities;

1- Mennu's Healing Ward - Heals Mennu for 1% of his total life every second.
2- Tainted Earthgrab Totem - Periodically casts an AoE Entangling Roots. Causes very low (~72 a tick on heroic) damage and has a relatively small range.
3- Tainted Stoneskin Totem - Gives Mennu a large boost in armor, reducing damage from melee.
4- Corrupted Nova Totem - Explodes after 5 secs for around 2,500 fire damage to everyone in a 10 yard radius of the totem.

-----------
Lightning Bolt - Deals 1,000 - 1,600 nature damage, cast only on the character who currently has aggro. Uninterruptible.
Heroic mode: Hits for about 2600-3200 nature damage, cast only on the character who currently has aggro. Uninterruptible.

Right now, the damage of the lightning bolt in Heroic mode is the same as Normal mode.

-----------

Corrupted Nova Totem: Heroic mode: Explodes after ~15 seconds or when destroyed for around 6500 fire damage in a 10 yard radius of the totem. Melee DPS should put on gear in which they get ~7.1k health so they can survive a higher end damage range if the totem is accidentally destroyed. Ranged DPS and healers should take care not to stand close to the totem because higher end damage will probably oneshot them.

Totem do nothing

-------------

https://wowwiki.fandom.com/wiki/Mennu_the_Betrayer

**Comment by sveN295** [comment]
Fixed.
