### ISSUE TITLE
[Heroic Slave Pens] Quagmirran [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#64]
He his doing Normal mode dmg even on Heroic mode. 

This guy hits fairly hard in melee, hitting an average geared tank for ~2.2k.

Getting attacked by him for 600ish on a half naked warrior tank

https://wowwiki.fandom.com/wiki/Quagmirran

**Comment by sveN295** [comment]
Doesn't sound like a script issue, Assigned to Jinnai.

**Comment by Jinnaix** [comment]
Fixed.
Passing the Issue back since Heroic version of [Poison Bolt Volley](https://www.wowhead.com/spell=39340/poison-bolt-volley) is not covered in script.
