### ISSUE TITLE
[Heroic Underbog] Hungarfen [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#65]
Ability: Foul Spores: 
At 20% health he roots himself and projects an AoE poison cloud which hits for between 400 and 600 damage every second. Hungarfen is then healed for 4x the physical damage done (spells still damage in the usual manner). 15 yard radius. These can be dispelled with Tranquilizing Shot!

I could interrupt this with a single shield bash which is not blizzlike. 

---------

When he hits 20% he will begin using Foul Spores. ALL party members, including the tank, should move away from Hungarfen so no one takes damage from the AoE, and he doesn't heal himself. (He heals based on the damage he does to nearby party members, so back off and burn)

Right now, he doesnt heal at all.

https://wowwiki.fandom.com/wiki/Hungarfen

**Comment by sveN295** [comment]
Fixed.
