### ISSUE TITLE
[Heroic and Normal Underbog] Swamplord Musel'ek & Claw [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#68]
How is it supposed to be: 
Triggering combat with Swamplord Musel'ek should trigger combat with his bear Claw.

How is it right now: 
Attacking Swamplord Musel'ek doesnt trigger combat with Claw. 

----------

Aimed Shot: Musel'ek will use this ability when nobody is in melee range. It can hit for over 2000 damage on cloth-wearing classes.

Very long cast that he auto interrupt himself from casting, just like Nefarian fear experience

------------

https://wowwiki.fandom.com/wiki/Swamplord_Musel%27ek

**Comment by sveN295** [comment]
Boss is scripted with SmartAI atm. Rewrote necessary.

**Comment by sveN295** [comment]
Fixed.
