### ISSUE TITLE
[Heroic and Normal Underbog] The Black Stalker [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#69]
Missing 1 ability;
Levitate: This effect brings a player in the air and when it wears off, a debuff will come on(Suspension)which lasts 20 seconds. However, it is dispellable. Players with ranged attacks can still attack the boss in mid air. Healers can be (but usually aren't) lifted high enough that the tank is out of range of heals.

https://wowwiki.fandom.com/wiki/The_Black_Stalker

**Comment by sveN295** [comment]
Workaround implemented. Fixed for now.
