### ISSUE TITLE
[Heroic and Normal Steamvault] Hydromancer Thespia [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#70]
Hydromancer Thespia is accompanied by two water elemental adds: Coilfang Water Elemental.

You can actually pull the left Water Elemental and the other one doesn't trigger combat. I've seen this a lot on other private servers but this is not blizzlike.

Both Water Elemental should trigger combat regardless of the way you initiate the fight. 

https://wowwiki.fandom.com/wiki/Hydromancer_Thespia

**Comment by sveN295** [comment]
Fixed.
