### ISSUE TITLE
[Heroic and Normal Steamvault] Mekgineer Steamrigger [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#71]
You can pull the boss with a ranged weapon and the gnomes around him doesnt trigger combat 

-------------------

Normal mode missing ability;
Gnome Repairers: A few times during the fight at 75%, 50% and 25% health, he will call upon 3-4 gnomes to heal him. These gnomes have 5k hp and deal 200-500 melee damage on hit. These are non-elite mobs and should receive all focus from DPS, to prevent boss from healing. The healing is a channeled spell which break on damage, and after it has been broken the gnome will start it again after a few seconds, so keep the DPS up.

----------

Heroic mode missing 2 abilities;
1- Steamrigger in heroic mode is almost identical to normal mode, except that an extra gnome 
appears every 7 seconds or so
2- Enrage: Enrages after 5 minutes (heroic mode only)

--------

https://wowwiki.fandom.com/wiki/Mekgineer_Steamrigger

**Comment by sveN295** [comment]
Fixed.
