### ISSUE TITLE
[Karazhan] Prince Malchezaar [Boss]

### ISSUE THREAD

**Issue by Evilanemesis** [Jinnaix/nemesis-bug-reporting#8]
Doesnt cast Enfeeble in phase 1 and 2;

Enfeeble (Phases One and Two)
Periodically casts Enfeeble on five characters chosen at random, excluding the current target (the tank). [Note: in parties of 5 or fewer, the Prince does not Enfeeble five characters/everyone. The person at the top of the hate list (presumably the tank) is still not targeted, and all others are Enfeebled.] Enfeeble reduces maximum health to a single hit point for about seven seconds. While this effect is active, any damage causes instant death. Healing effects do nothing, but the lost health returns after this undispellable effect ends. Enfeeble is followed by a Shadow Nova, so enfeebled characters must stay 30+ yards away from Malchezaar, and watch out for Infernals. Vampiric effects such as Siphon Life ignore Enfeeble. This does not hit pets.

https://wowwiki.fandom.com/wiki/Prince_Malchezaar

**Comment by sveN295** [comment]
He does cast enfeeble but not on the tank so you have to have more than one person in combat with him to check. 

I tested it with 2 characters and he casts it like he should.
