### ISSUE TITLE
[Black Morass] Time Portal Adds are misbehaving

### ISSUE THREAD

**Issue by sveN295** [Jinnaix/nemesis-bug-reporting#81]
**Description:**

The adds that are spawning are not running to Medivh's portal. They are attacking it from where they spawn.

They have to run to Medivh's portal and once they get to melee range, they start attacking it.

Summoning Time Keeper last too long. It's supposed to stay there and help for couple waves max. 

Last boss doesnt run to Medivh's portal which he should do.

https://wowwiki.fandom.com/wiki/Black_Morass

**Comment by sveN295** [comment]
A bit of research:

The portals spawn Time Dragons that cast "Corrupt Medivh" when out of combat - this damages Medivh and is the failure mode of the dungeon (If Medivh dies, you lose).

For example on this creature:

`SELECT * FROM smart_scripts WHERE entryorguid = 17835`

This is handled with Smart AI. 

According to the issue report, they are supposed to run to Medivh before they cast this.

**Comment by Jinnaix** [comment]
Closed by #https://github.com/Jinnaix/Nemesis/commit/5338f0620463996cb1f3cacf66aa46684530646f
