### ISSUE TITLE
[EVENT] Honor Hold Hellfire 

### ISSUE THREAD

**Issue by Jinnaix** [Jinnaix/nemesis-bug-reporting#92]
**Description:**

Duo to a current Core Bug, grouped feared NPCs don´t return to their Home position after fear runs out.

**Current behaviour:**

After fear ends, NPC stay where they are instead of returning back to home.

**To Do:**

Disable [Fear](https://github.com/sveN295/Nemesis/blob/335C/src/server/scripts/Outland/zone_hellfire_peninsula.cpp#L1196) from Honor Hold event for now until Core Support of this behavior.

**Comment by sveN295** [comment]
Fear is disabled.
